package org.phoenixctms.ctsms.web.util;

import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.TimeZone;

import org.phoenixctms.ctsms.enumeration.AuthenticationType;
import org.phoenixctms.ctsms.enumeration.Color;
import org.phoenixctms.ctsms.enumeration.ECRFFieldStatusQueue;
import org.phoenixctms.ctsms.enumeration.EventImportance;
import org.phoenixctms.ctsms.enumeration.InputFieldType;
import org.phoenixctms.ctsms.enumeration.PaymentMethod;
import org.phoenixctms.ctsms.enumeration.RandomizationMode;
import org.phoenixctms.ctsms.enumeration.Sex;
import org.phoenixctms.ctsms.enumeration.VariablePeriod;
import org.phoenixctms.ctsms.util.CommonUtil;
import org.phoenixctms.ctsms.web.util.DateUtil.DurationUnitOfTime;

public final class DefaultSettings {

	public final static String THEME = "aristo";
	public final static int MAX_CRITERIONS = 30;
	public final static String CALENDAR_YEAR_RANGE = "1900:" + ((new GregorianCalendar()).get(GregorianCalendar.YEAR) + 10);
	public final static String IBAN_MASK = "";
	public static final boolean HIDE_DETAILED_AUTHENTICATION_ERROR = true;
	public final static int COMMENT_CLIP_MAX_LENGTH = 30;
	public final static int DEFAULT_CLIP_MAX_LENGTH = 30;
	public final static int PICKER_CLIP_MAX_LENGTH = 20;
	public final static int MENU_ITEM_LABEL_CLIP_MAX_LENGTH = 30;
	public final static Color NA_STATUS_COLOR = Color.CRIMSON;
	public static final Boolean SHOW_HOLIDAYS = null; // both
	public final static int SESSION_TIMEOUT = 60;
	public final static int SESSION_TIMEOUT_TRUSTED = 60;
	public final static String META_DESCRIPTION = "{0}";
	public final static String CONTACT_EMAIL = "nobody@{0}";
	public final static String API_REALM = "api";
	public final static String API_TITLE = "REST API";
	public static final boolean API_TRUSTED_HOSTS_ONLY = true;
	public final static String API_VERSION = "0.0.0";
	public static final boolean ENABLE_TOOLTIPS = true;
	public static final boolean TRIAL_STATUS_UPDATE_REQUIRES_PASSWORD = true;
	public static final boolean ECRF_STATUS_UPDATE_REQUIRES_PASSWORD = true;
	public final static ArrayList<String> ECRF_FIELD_VALUES_PAGE_SIZES = new ArrayList<String>();
	public final static ArrayList<String> GROUP_VISIT_MATRIX_PAGE_SIZES = new ArrayList<String>();
	public final static ArrayList<String> INQUIRY_VALUES_PAGE_SIZES = new ArrayList<String>();
	public final static ArrayList<String> DUMMY_INQUIRY_VALUES_PAGE_SIZES = new ArrayList<String>();
	public final static ArrayList<String> PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES = new ArrayList<String>();
	public final static Color INVENTORY_MAINTENANCE_OVERDUE_COLOR = Color.CRIMSON;
	public final static ArrayList<String> INVENTORY_MAINTENANCE_DUE_IN_DURATIONS = new ArrayList<String>();
	public final static ArrayList<String> INVENTORY_MAINTENANCE_DUE_IN_COLORS = new ArrayList<String>();
	public final static Color COURSE_EXPIRATION_OVERDUE_COLOR = Color.CRIMSON;
	public final static ArrayList<String> COURSE_EXPIRATION_DUE_IN_DURATIONS = new ArrayList<String>();
	public final static ArrayList<String> COURSE_EXPIRATION_DUE_IN_COLORS = new ArrayList<String>();
	public final static Color TIMELINE_EVENT_OVERDUE_COLOR = Color.CRIMSON;
	public final static ArrayList<String> TIMELINE_EVENT_DUE_IN_DURATIONS = new ArrayList<String>();
	public final static ArrayList<String> TIMELINE_EVENT_DUE_IN_COLORS = new ArrayList<String>();
	public final static Color PROBAND_AUTO_DELETE_OVERDUE_COLOR = Color.CRIMSON;
	public final static ArrayList<String> PROBAND_AUTO_DELETE_DUE_IN_DURATIONS = new ArrayList<String>();
	public final static ArrayList<String> PROBAND_AUTO_DELETE_DUE_IN_COLORS = new ArrayList<String>();
	public final static ArrayList<String> TRUSTED_REFERER_HOSTS = new ArrayList<String>();
	public final static String LOCAL_ADDR_REFERER = "LOCAL_ADDR";
	public final static String LOCAL_NAME_REFERER = "LOCAL_NAME";
	public final static String HTTP_DOMAIN_REFERER = "HTTP_DOMAIN_REFERER";
	static {
		INVENTORY_MAINTENANCE_DUE_IN_DURATIONS.add(Long.toString(1 * 24 * 60 * 60));
		INVENTORY_MAINTENANCE_DUE_IN_COLORS.add(Color.ORANGERED.name());
		INVENTORY_MAINTENANCE_DUE_IN_DURATIONS.add(Long.toString(3 * 24 * 60 * 60));
		INVENTORY_MAINTENANCE_DUE_IN_COLORS.add(Color.TOMATO.name());
		INVENTORY_MAINTENANCE_DUE_IN_DURATIONS.add(Long.toString(7 * 24 * 60 * 60));
		INVENTORY_MAINTENANCE_DUE_IN_COLORS.add(Color.CORAL.name());
		COURSE_EXPIRATION_DUE_IN_DURATIONS.add(Long.toString(1 * 24 * 60 * 60));
		COURSE_EXPIRATION_DUE_IN_COLORS.add(Color.ORANGERED.name());
		COURSE_EXPIRATION_DUE_IN_DURATIONS.add(Long.toString(3 * 24 * 60 * 60));
		COURSE_EXPIRATION_DUE_IN_COLORS.add(Color.TOMATO.name());
		COURSE_EXPIRATION_DUE_IN_DURATIONS.add(Long.toString(7 * 24 * 60 * 60));
		COURSE_EXPIRATION_DUE_IN_COLORS.add(Color.CORAL.name());
		TIMELINE_EVENT_DUE_IN_DURATIONS.add(Long.toString(1 * 24 * 60 * 60));
		TIMELINE_EVENT_DUE_IN_COLORS.add(Color.ORANGERED.name());
		TIMELINE_EVENT_DUE_IN_DURATIONS.add(Long.toString(3 * 24 * 60 * 60));
		TIMELINE_EVENT_DUE_IN_COLORS.add(Color.TOMATO.name());
		TIMELINE_EVENT_DUE_IN_DURATIONS.add(Long.toString(7 * 24 * 60 * 60));
		TIMELINE_EVENT_DUE_IN_COLORS.add(Color.CORAL.name());
		PROBAND_AUTO_DELETE_DUE_IN_DURATIONS.add(Long.toString(1 * 24 * 60 * 60));
		PROBAND_AUTO_DELETE_DUE_IN_COLORS.add(Color.ORANGERED.name());
		PROBAND_AUTO_DELETE_DUE_IN_DURATIONS.add(Long.toString(3 * 24 * 60 * 60));
		PROBAND_AUTO_DELETE_DUE_IN_COLORS.add(Color.TOMATO.name());
		PROBAND_AUTO_DELETE_DUE_IN_DURATIONS.add(Long.toString(7 * 24 * 60 * 60));
		PROBAND_AUTO_DELETE_DUE_IN_COLORS.add(Color.CORAL.name());
		TRUSTED_REFERER_HOSTS.add("localhost");
		TRUSTED_REFERER_HOSTS.add("127.0.0.7");
		TRUSTED_REFERER_HOSTS.add(LOCAL_ADDR_REFERER);
		TRUSTED_REFERER_HOSTS.add(LOCAL_NAME_REFERER);
		TRUSTED_REFERER_HOSTS.add(HTTP_DOMAIN_REFERER);
		ECRF_FIELD_VALUES_PAGE_SIZES.add("1");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("2");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("3");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("4");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("5");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("6");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("7");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("8");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("9");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("10");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("11");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("12");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("13");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("14");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("15");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("16");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("17");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("18");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("19");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("20");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("30");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("50");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("100");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("300");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("500");
		ECRF_FIELD_VALUES_PAGE_SIZES.add("1000");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("4");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("10");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("20");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("30");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("50");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("100");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("300");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("500");
		GROUP_VISIT_MATRIX_PAGE_SIZES.add("1000");
		INQUIRY_VALUES_PAGE_SIZES.add("4");
		INQUIRY_VALUES_PAGE_SIZES.add("10");
		INQUIRY_VALUES_PAGE_SIZES.add("20");
		INQUIRY_VALUES_PAGE_SIZES.add("30");
		INQUIRY_VALUES_PAGE_SIZES.add("50");
		INQUIRY_VALUES_PAGE_SIZES.add("100");
		INQUIRY_VALUES_PAGE_SIZES.add("300");
		INQUIRY_VALUES_PAGE_SIZES.add("500");
		INQUIRY_VALUES_PAGE_SIZES.add("1000");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("4");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("10");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("20");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("30");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("50");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("100");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("300");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("500");
		PROBAND_LIST_ENTRY_TAG_VALUES_PAGE_SIZES.add("1000");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("4");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("10");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("20");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("30");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("50");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("100");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("300");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("500");
		DUMMY_INQUIRY_VALUES_PAGE_SIZES.add("1000");
	}
	public final static VariablePeriod COURSE_EXPIRATION_REMINDER_PERIOD = VariablePeriod.THREE_MONTHS;
	public static final Long COURSE_EXPIRATION_REMINDER_PERIOD_DAYS = null;
	public static final Color USER_LOCKED_COLOR = Color.CRIMSON;
	public static final Color PASSWORD_VALID_COLOR = Color.LIGHTGREEN;
	public static final Color PASSWORD_INVALID_COLOR = Color.SALMON;
	public final static Color COURSE_SOME_CANCELLED = Color.RED;
	public final static Color COURSE_ALL_ACK_COMPLETED = Color.LIGHTGREEN;
	public final static Color COURSE_SOME_ACK = Color.ORANGE;
	public final static Color COURSE_NONE_ACK_YET = Color.YELLOW;
	public final static Color COURSE_SOME_FAILED_NACK_CANCELLED = Color.DARKORANGE;
	public static final int INPUT_MODEL_VALUE_TEXT_CLIP_MAX_LENGTH = 30;
	public static final int AUDIT_TRAIL_FIELD_VALUE_TEXT_CLIP_MAX_LENGTH = 72;
	public static final Color INPUT_MODEL_NOT_EDITABLE_COLOR = Color.WHITESMOKE;
	public static final Color INPUT_MODEL_NEW_COLOR = Color.MISTYROSE;
	public static final Color INPUT_MODEL_CREATED_COLOR = null;
	public static final Color INPUT_MODEL_DUMMY_COLOR = Color.SNOW;
	public static final int INPUT_MODEL_LONG_TITLE_LENGTH = 36;
	public static final EventImportance TIMELINE_EVENT_IMPORTANCE_PRESET = EventImportance.NORMAL;
	public static final boolean TIMELINE_EVENT_NOTIFY_PRESET = true;
	public static final boolean TIMELINE_EVENT_DISMISSED_PRESET = false;
	public static final boolean TIMELINE_EVENT_SHOW_PRESET = true;
	public static final VariablePeriod TIMELINE_EVENT_REMINDER_PERIOD_PRESET = VariablePeriod.EXPLICIT;
	public static final Long TIMELINE_EVENT_REMINDER_PERIOD_DAYS_PRESET = 7l;
	public static final boolean PROBAND_GROUP_RANDOMIZE_PRESET = false;
	public static final float VISIT_REIMBURSEMENT_PRESET = 0.0f;
	public static final VariablePeriod SHIFT_DURATION_SUMMARY_PERIOD_AFTER = VariablePeriod.EXPLICIT;
	public static final Long SHIFT_DURATION_SUMMARY_PERIOD_AFTER_DAYS = 14l;
	public static final VariablePeriod SHIFT_DURATION_SUMMARY_PERIOD_BEFORE = VariablePeriod.EXPLICIT;
	public static final Long SHIFT_DURATION_SUMMARY_PERIOD_BEFORE_DAYS = 14l;
	public static final VariablePeriod BOOKING_DURATION_SUMMARY_PERIOD_AFTER = VariablePeriod.EXPLICIT;
	public static final Long BOOKING_DURATION_SUMMARY_PERIOD_AFTER_DAYS = 14l;
	public static final VariablePeriod BOOKING_DURATION_SUMMARY_PERIOD_BEFORE = VariablePeriod.EXPLICIT;
	public static final Long BOOKING_DURATION_SUMMARY_PERIOD_BEFORE_DAYS = 14l;
	public static final boolean INVENTORY_MAINTENANCE_ACTIVE_PRESET = true;
	public static final float INVENTORY_MAINTENANCE_CHARGE_PRESET = 0.0f;
	public static final boolean INVENTORY_MAINTENANCE_RECURRING_PRESET = false;
	public static final boolean INVENTORY_MAINTENANCE_NOTIFY_PRESET = true;
	public static final boolean INVENTORY_MAINTENANCE_DISMISSED_PRESET = false;
	public static final VariablePeriod INVENTORY_MAINTENANCE_RECURRENCE_PERIOD_PRESET = VariablePeriod.YEAR;
	public static final Long INVENTORY_MAINTENANCE_RECURRENCE_PERIOD_DAYS_PRESET = null;
	public static final VariablePeriod INVENTORY_MAINTENANCE_REMINDER_PERIOD_PRESET = VariablePeriod.EXPLICIT;
	public static final Long INVENTORY_MAINTENANCE_REMINDER_PERIOD_DAYS_PRESET = 7l;
	public final static boolean COURSE_SELF_REGISTRATION_PRESET = true;
	public final static boolean COURSE_EXPIRES_PRESET = false;
	public final static Long COURSE_MAX_NUMBER_OF_PARTICIPANTS_PRESET = null;
	public final static boolean COURSE_SHOW_CV_PRESET_PRESET = false;
	public final static boolean COURSE_SHOW_TRAINING_RECORD_PRESET_PRESET = false;
	public final static boolean COURSE_CERTIFICATE_PRESET = false;
	public final static boolean COURSE_SHOW_COMMENT_CV_PRESET_PRESET = false;
	public final static int COURSE_DURATION_DAYS_PRESET = 0;
	public final static Integer COURSE_DEADLINE_START_DAYS_PRESET = null;
	public static final VariablePeriod COURSE_VALIDITY_PERIOD_PRESET = VariablePeriod.YEAR;
	public static final Long COURSE_VALIDITY_PERIOD_DAYS_PRESET = null;
	public static final boolean STAFF_ALLOCATABLE_PRESET = false;
	public static final boolean STAFF_EMPLOYEE_PRESET = false;
	public static final boolean STAFF_SUPERVISOR_PRESET = false;
	public static final boolean STAFF_PERSON_PRESET = true;
	public static final Sex STAFF_GENDER_PRESET = null;
	public static final long STAFF_MAX_OVERLAPPING_PRESET = 1;
	public static final Sex PROBAND_GENDER_PRESET = null;
	public static final float MONEY_TRANSFER_AMOUNT_PRESET = 0.0f;
	public static final PaymentMethod MONEY_TRANSFER_METHOD_PRESET = null;
	public static final boolean MONEY_TRANSFER_PAID_PRESET = false;
	public static final boolean MONEY_TRANSFER_SHOW_COMMENT_PRESET = false;
	public static final Boolean PROBAND_MONEY_TRANSFER_SUMMARY_SHOW_PAID_PRESET = false;
	public static final Boolean TRIAL_MONEY_TRANSFER_SUMMARY_SHOW_PAID_PRESET = null;
	public static final boolean TRIAL_MONEY_TRANSFER_SUMMARY_ACTIVE_IDENTITY_DEPARTMENT_PRESET = true;
	public static final boolean ECRF_PROGRESS_SUMMARY_ACTIVE_IDENTITY_DEPARTMENT_PRESET = true;
	public static final boolean INPUT_FIELD_LOCALIZED_PRESET = false;
	public static final boolean INPUT_FIELD_USER_TIMEZONE_PRESET = false;
	public static final InputFieldType INPUT_FIELD_FIELD_TYPE_PRESET = null;
	public static final boolean INPUT_FIELD_BOOLEAN_PRESET_PRESET = false;
	public static final Integer INPUT_FIELD_MAX_SELECTIONS_PRESET = null;
	public static final Integer INPUT_FIELD_MIN_SELECTIONS_PRESET = null;
	public static final String INPUT_FIELD_REGEXP_PRESET = null;
	public static final String INPUT_FIELD_TEXT_PRESET_PRESET = null;
	public static final Date INPUT_FIELD_DATE_PRESET_PRESET = null;
	public static final Float INPUT_FIELD_FLOAT_LOWER_LIMIT_PRESET = null;
	public static final Float INPUT_FIELD_FLOAT_PRESET_PRESET = null;
	public static final Float INPUT_FIELD_FLOAT_UPPER_LIMIT_PRESET = null;
	public static final Long INPUT_FIELD_LONG_LOWER_LIMIT_PRESET = null;
	public static final Long INPUT_FIELD_LONG_PRESET_PRESET = null;
	public static final Long INPUT_FIELD_LONG_UPPER_LIMIT_PRESET = null;
	public static final Date INPUT_FIELD_MAX_DATE_PRESET = null;
	public static final Date INPUT_FIELD_MAX_TIMESTAMP_PRESET = null;
	public static final Date INPUT_FIELD_MIN_DATE_PRESET = null;
	public static final Date INPUT_FIELD_MIN_TIMESTAMP_PRESET = null;
	public static final Date INPUT_FIELD_TIMESTAMP_PRESET_PRESET = null;
	public static final boolean INPUT_FIELD_LEARN_PRESET = false;
	public static final boolean INPUT_FIELD_STRICT_PRESET = false;
	public static final long INPUT_FIELD_SKETCH_WIDTH_PRESET = 300;
	public static final long INPUT_FIELD_SKETCH_HEIGHT_PRESET = 100;
	public static final Date INPUT_FIELD_MIN_TIME_PRESET = null;
	public static final Date INPUT_FIELD_MAX_TIME_PRESET = null;
	public static final Date INPUT_FIELD_TIME_PRESET_PRESET = null;
	public static final boolean INPUT_FIELD_SELECTION_SET_VALUE_LOCALIZED_PRESET = false;
	public final static boolean USER_LOCKED_PRESET = false;
	public final static boolean USER_DECRYPT_PRESET = true;
	public final static boolean USER_DECRYPT_UNTRUSTED_PRESET = false;
	public static final String USER_LOCALE_PRESET = CommonUtil.localeToString(Locale.getDefault());
	public static final String USER_TIME_ZONE_PRESET = CommonUtil.timeZoneToString(TimeZone.getDefault());
	public static final String USER_THEME_PRESET = "aristo";
	public static final AuthenticationType USER_AUTH_METHOD_PRESET = AuthenticationType.LOCAL;
	public final static boolean USER_SHOW_TOOLTIPS_PRESET = true;
	public final static boolean HYPERLINK_ACTIVE_PRESET = true;
	public final static String HYPERLINK_URL_PRESET = "http://";
	public final static boolean FILE_ACTIVE_PRESET = true;
	public final static boolean FILE_PUBLIC_PRESET = false;
	public final static String FILE_LOGICAL_PATH_PRESET = "";
	public static final String SCHEDULE_TIME_PATTERN = "HH:mm";
	public static final String SCHEDULE_RIGHT_HEADER_TEMPLATE = "month,agendaWeek,agendaDay";
	public final static int MAX_RECENT_ENTITIES = 10;
	public static final int EXPIRATION_INFO_DAYS = 14;
	public static final long EXPIRATION_INFO_LOGONS_LEFT = 3;
	public static final int TRUSTED_HOST_LOGON_ATTEMPTS_CAPTCHA_REQUIRED_LIMIT = 2; // -1: disable captcha
	public static final int UNTRUSTED_HOST_LOGON_ATTEMPTS_CAPTCHA_REQUIRED_LIMIT = 1; // -1: disable captcha
	public final static int BOOKING_DURATION_MINUTES_PRESET = 60;
	public final static int DUTY_ROSTER_TURN_DURATION_MINUTES_PRESET = 60;
	public static final Boolean PROBAND_LIST_INQUIRY_ACTIVE = true;
	public static final int PROBAND_LIST_INQUIRY_VALUE_TEXT_CLIP_MAX_LENGTH = 30;
	public static final int PROBAND_LIST_PROBAND_LIST_ENTRY_TAG_VALUE_TEXT_CLIP_MAX_LENGTH = 30;
	public static final int STRATIFICATION_RANDOMIZATION_LIST_PROBAND_LIST_ENTRY_TAG_VALUE_TEXT_CLIP_MAX_LENGTH = 200;
	public static final boolean DUTY_ROSTER_SELF_ALLOCATABLE_PRESET = true;
	public static final boolean TIMELINE_SCHEDULE_IDENTITY_TEAM_MEMBER_PRESET = true;
	public static final boolean TEAM_MEMBER_ACCESS_PRESET = true;
	public static final boolean TEAM_MEMBER_SIGN_PRESET = false;
	public static final boolean TEAM_MEMBER_RESOLVE_PRESET = false;
	public static final boolean TEAM_MEMBER_VERIFY_PRESET = false;
	public static final boolean TEAM_MEMBER_NOTIFY_TIMELINE_EVENT_PRESET = true;
	public static final boolean TEAM_MEMBER_NOTIFY_ECRF_VALIDATED_STATUS_PRESET = false;
	public static final boolean TEAM_MEMBER_NOTIFY_ECRF_REVIEW_STATUS_PRESET = false;
	public static final boolean TEAM_MEMBER_NOTIFY_ECRF_VERIFIED_STATUS_PRESET = false;
	public static final boolean TEAM_MEMBER_NOTIFY_ECRF_FIELD_STATUS_PRESET = false;
	public static final boolean TEAM_MEMBER_NOTIFY_OTHER_PRESET = false;
	public static final boolean STAFF_CONTACT_NOTIFY_PRESET = true;
	public static final boolean STAFF_CONTACT_NA_PRESET = false;
	public final static boolean STAFF_ADDRESS_AFNUS_PRESET = false;
	public final static boolean STAFF_ADDRESS_CV_PRESET = false;
	public final static boolean STAFF_ADDRESS_DELIVER_PRESET = true;
	public static final boolean PROBAND_LIST_ENTRY_TAG_DISABLED_PRESET = false;
	public static final boolean PROBAND_LIST_ENTRY_TAG_OPTIONAL_PRESET = false;
	public static final boolean PROBAND_LIST_ENTRY_TAG_EXCEL_PRESET = true;
	public static final boolean PROBAND_LIST_ENTRY_TAG_ECRF_PRESET = true;
	public static final boolean PROBAND_LIST_ENTRY_TAG_STRATIFICATION_PRESET = false;
	public static final boolean PROBAND_LIST_ENTRY_TAG_RANDOMIZE_PRESET = false;
	public static final boolean PROBAND_CONTACT_NOTIFY_PRESET = true;
	public static final boolean PROBAND_CONTACT_NA_PRESET = false;
	public final static boolean PROBAND_ADDRESS_AFNUS_PRESET = false;
	public final static boolean PROBAND_ADDRESS_DELIVER_PRESET = true;
	public static final boolean MAINTENANCE_SCHEDULE_IDENTITY_RESPONSIBLE_PERSON_PRESET = true;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_HOLIDAYS_PRESET = true;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_BOOKINGS_PRESET = true;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_INVENTORY_STATUS_PRESET = false;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_PROBAND_STATUS_PRESET = false;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_MAINTENANCE_ITEMS_PRESET = true;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_SHOW_COURSES_PRESET = false;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_SHOW_VISIT_SCHEDULE_PRESET = true;
	public static final Long INVENTORY_BOOKING_SCHEDULE_SHOW_COLLISIONS_THRESHOLD_DAYS = 7l;
	public static final boolean INVENTORY_BOOKABLE_PRESET = false;
	public static final long INVENTORY_PIECES_PRESET = 1;
	public static final long INVENTORY_MAX_OVERLAPPING_PRESET = 1;
	public static final boolean INQUIRY_ACTIVE_PRESET = true;
	public static final boolean INQUIRY_ACTIVE_SIGNUP_PRESET = true;
	public static final boolean INQUIRY_DISABLED_PRESET = false;
	public static final boolean INQUIRY_OPTIONAL_PRESET = false;
	public static final boolean INQUIRY_EXCEL_PRESET = true;
	public static final boolean ECRF_FIELD_OPTIONAL_PRESET = false;
	public static final boolean ECRF_FIELD_AUDIT_TRAIL_PRESET = true;
	public static final boolean ECRF_FIELD_SERIES_PRESET = false;
	public static final boolean ECRF_FIELD_DISABLED_PRESET = false;
	public static final boolean ECRF_ACTIVE_PRESET = true;
	public static final boolean ECRF_DISABLED_PRESET = false;
	public static final boolean ECRF_ENABLE_BROWSER_FIELD_CALCULATION_PRESET = true;
	public static final float ECRF_CHARGE_PRESET = 0.0f;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_HOLIDAYS_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_DUTY_ROSTER_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_STAFF_STATUS_PRESET = false;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_COURSE_BOOKINGS_PRESET = false;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_VISIT_SCHEDULE_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_TIMELINE_EVENTS_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_COURSES_PRESET = false;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_PROBAND_STATUS_PRESET = false;
	public static final Long DUTY_ROSTER_SCHEDULE_SHOW_COLLISIONS_THRESHOLD_DAYS = 7l;
	public static final boolean INPUT_FIELD_DUMMY_OPTIONAL_PRESET = false;
	public static final boolean INPUT_FIELD_DUMMY_DISABLED_PRESET = false;
	public final static boolean ENABLE_PRIMEFACES_SCHEDULE_DST_WORKAROUND = true; // still required 2012-03+
	public final static boolean DATE_TIME_USER_TIME_ZONE = true;
	public final static boolean DATE_USER_TIME_ZONE = true;
	public final static boolean TIME_USER_TIME_ZONE = true;
	public final static boolean CV_POSITION_SHOW_COMMENT_CV_PRESET = false;
	public final static boolean CV_POSITION_SHOW_CV_PRESET = true;
	public static final boolean BANK_ACCOUNT_ACTIVE_PRESET = true;
	public static final boolean BANK_ACCOUNT_NA_PRESET = false;
	public static final Boolean NOTIFICATIONS_OBSOLETE = null;
	public static final Boolean NOTIFICATIONS_SEND = null;
	public static final Boolean NOTIFICATIONS_SHOW = true;
	public static final Boolean NOTIFICATIONS_SENT = null;
	public static final Boolean NOTIFICATIONS_DROPPED = null;
	public static final boolean INVENTORY_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = false;
	public static final boolean STAFF_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = false;
	public static final boolean COURSE_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = false;
	public static final boolean TRIAL_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = true;
	public static final boolean PROBAND_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = false;
	public static final boolean MASS_MAIL_FILE_FOLDER_TREE_DYNAMIC_DEFAULT = false;
	public static final String INVENTORY_START_URL = "/inventory/inventorySearch.jsf";
	public static final String STAFF_START_URL = "/staff/staffSearch.jsf";
	public static final String COURSE_START_URL = "/course/courseSearch.jsf";
	public static final String USER_START_URL = "/user/userSearch.jsf";
	public static final String TRIAL_START_URL = "/trial/trialSearch.jsf";
	public static final String PROBAND_START_URL = "/proband/probandSearch.jsf";
	public static final String INPUT_FIELD_START_URL = "/inputfield/inputFieldSearch.jsf";
	public static final String MASS_MAIL_START_URL = "/massmail/massMailSearch.jsf";
	public static final Integer GRAPH_MAX_STAFF_INSTANCES = 100;
	public static final boolean GRAPH_STAFF_BREADTH_FIRST = true;
	public static final Integer GRAPH_MAX_STAFF_PARENT_DEPTH = 5;
	public static final Integer GRAPH_MAX_STAFF_CHILDREN_DEPTH = 5;
	public static final Integer GRAPH_MAX_COURSE_INSTANCES = 100;
	public static final Integer GRAPH_MAX_RENEWALS_DEPTH = 2;
	public static final Integer GRAPH_MAX_PRECEDING_DEPTH = 2;
	public static final boolean GRAPH_COURSE_BREADTH_FIRST = true;
	public static final Integer GRAPH_MAX_INVENTORY_INSTANCES = 100;
	public static final Integer GRAPH_MAX_INVENTORY_PARENT_DEPTH = 5;
	public static final Integer GRAPH_MAX_INVENTORY_CHILDREN_DEPTH = 5;
	public static final boolean GRAPH_INVENTORY_BREADTH_FIRST = true;
	public static final boolean GRAPH_PROBAND_BREADTH_FIRST = true;
	public static final Integer GRAPH_MAX_PROBAND_INSTANCES = 100;
	public static final Integer GRAPH_MAX_PROBAND_PARENTS_DEPTH = 2;
	public static final Integer GRAPH_MAX_PROBAND_CHILDREN_DEPTH = 2;
	public static final Integer API_GRAPH_MAX_STAFF_INSTANCES = 100;
	public static final Integer API_GRAPH_MAX_STAFF_PARENT_DEPTH = 5;
	public static final Integer API_GRAPH_MAX_STAFF_CHILDREN_DEPTH = 5;
	public static final Integer API_GRAPH_MAX_INVENTORY_INSTANCES = 100;
	public static final Integer API_GRAPH_MAX_INVENTORY_PARENT_DEPTH = 5;
	public static final Integer API_GRAPH_MAX_INVENTORY_CHILDREN_DEPTH = 5;
	public static final Integer API_GRAPH_MAX_COURSE_INSTANCES = 100;
	public static final Integer API_GRAPH_MAX_RENEWALS_DEPTH = 2;
	public static final Integer API_GRAPH_MAX_PRECEDING_DEPTH = 2;
	public static final Integer API_GRAPH_MAX_PROBAND_INSTANCES = 100;
	public static final Integer API_GRAPH_MAX_PROBAND_PARENTS_DEPTH = 2;
	public static final Integer API_GRAPH_MAX_PROBAND_CHILDREN_DEPTH = 2;
	public static final boolean TIMELINE_SHOW_ALL_PRESET = false;
	public static final boolean TIMELINE_SHOW_DESCRIPTION_PRESET = false;
	public static final boolean TIMELINE_SHOW_START_STOP_PRESET = true;
	public static final DurationUnitOfTime DEFAULT_MOST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.DAYS;
	public static final DurationUnitOfTime DEFAULT_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.MINUTES;
	public static final int DEFAULT_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME_DECIMALS = 0;
	public static final DurationUnitOfTime SHIFT_MOST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.HOURS;
	public static final DurationUnitOfTime SHIFT_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.HOURS;
	public static final int SHIFT_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME_DECIMALS = 1;
	public static final DurationUnitOfTime STATUS_ENTRY_MOST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.DAYS;
	public static final DurationUnitOfTime STATUS_ENTRY_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.HOURS;
	public static final int STATUS_ENTRY_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME_DECIMALS = 0;
	public static final DurationUnitOfTime BOOKING_MOST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.HOURS;
	public static final DurationUnitOfTime BOOKING_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.HOURS;
	public static final int BOOKING_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME_DECIMALS = 1;
	public static final DurationUnitOfTime EXPIRATION_MOST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.DAYS;
	public static final DurationUnitOfTime EXPIRATION_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME = DurationUnitOfTime.DAYS;
	public static final int EXPIRATION_LEAST_SIGNIFICANT_DURATION_UNIT_OF_TIME_DECIMALS = 1;
	public static final VariablePeriod PROBAND_AUTODELETE_REMINDER_PERIOD = VariablePeriod.MONTH;
	public static final Long PROBAND_AUTODELETE_REMINDER_PERIOD_DAYS = null;
	public static final int INQUIRY_INPUTS_GRID_COLUMNS_THRESHOLD_WIDTH = 800;
	public static final int PROBAND_LIST_TAG_INPUTS_GRID_COLUMNS_THRESHOLD_WIDTH = 400;
	public static final int ECRF_FIELD_INPUTS_GRID_COLUMNS_THRESHOLD_WIDTH = 800;
	public static final Integer MAX_TAG_CLOUD_ITEMS = 10;
	public static final float MAX_TAG_CLOUD_ITEM_STRENGTH = 10;
	public static final int TAG_CLOUD_ITEM_LABEL_LENGTH = 20;
	public static final boolean STAFF_IMAGE_SHOW_CV_PRESET = true;
	public static final int INQUIRY_VALUES_DEFAULT_PAGE_SIZE = 10;
	public static final int INQUIRY_VALUES_DEFAULT_FIELDS_PER_ROW = 2;
	public static final int DUMMY_INQUIRY_VALUES_DEFAULT_PAGE_SIZE = 5;
	public static final int DUMMY_INQUIRY_VALUES_DEFAULT_FIELDS_PER_ROW = 1;
	public static final int PROBAND_LIST_ENTRY_TAG_VALUES_DEFAULT_PAGE_SIZE = 4;
	public static final int PROBAND_LIST_ENTRY_TAG_VALUES_DEFAULT_FIELDS_PER_ROW = 2;
	public static final int ECRF_FIELD_VALUES_DEFAULT_PAGE_SIZE = 10;
	public static final int ECRF_FIELD_VALUES_DEFAULT_FIELDS_PER_ROW = 3;
	public static final int SELECTION_ITEMS_TEXT_CLIP_MAX_LENGTH = 56;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_ACTIVE_IDENTITY_DEPARTMENT_PRESET = true;
	public static final boolean TIMELINE_ACTIVE_IDENTITY_DEPARTMENT_PRESET = true;
	public static final VariablePeriod ADMIN_COURSE_EXPIRATION_REMINDER_PERIOD = VariablePeriod.YEAR;
	public static final Long ADMIN_COURSE_EXPIRATION_REMINDER_PERIOD_DAYS = null;
	public static final boolean DUTY_ROSTER_SCHEDULE_ACTIVE_IDENTITY_DEPARTMENT_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_ACTIVE_IDENTITY_PRESET = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_UNASSIGED_DUTIES = true;
	public static final boolean DUTY_ROSTER_SCHEDULE_SHOW_ALL_COURSE_INVENTORY_BOOKINGS = true;
	public static final boolean INVENTORY_BOOKING_SCHEDULE_ACTIVE_IDENTITY_PRESET = true;
	public static final boolean TIMELINE_SCHEDULE_SHOW_NOTIFY_ONLY_PRESET = true;
	public static final boolean TIMELINE_SCHEDULE_IGNORE_OBSOLETE_PRESET = true;
	public static final boolean PROBAND_STATUS_IGNORE_OBSOLETE_PRESET = true;
	public static final boolean STAFF_STATUS_IGNORE_OBSOLETE_PRESET = true;
	public static final boolean MAINTENANCE_SCHEDULE_SHOW_NOTIFY_ONLY_PRESET = true;
	public static final boolean INVENTORY_STATUS_IGNORE_OBSOLETE_PRESET = true;
	public static final boolean INVENTORY_STATUS_SHOW_INACTIVE_ONLY_PRESET = true;
	public static final boolean PROBAND_STATUS_SHOW_INACTIVE_ONLY_PRESET = true;
	public static final boolean STAFF_STATUS_SHOW_INACTIVE_ONLY_PRESET = true;
	public static final boolean TRIAL_DUTY_SELF_ALLOCATION_LOCKED_PRESET = true;
	public static final boolean TRIAL_EXCLUSIVE_PROBANDS_PRESET = false;
	public static final boolean TRIAL_SIGNUP_PROBAND_LIST_PRESET = false;
	public static final boolean TRIAL_SIGNUP_INQUIRIES_PRESET = false;
	public static final boolean TRIAL_SIGNUP_RANDOMIZE_PRESET = false;
	public static final VariablePeriod TRIAL_BLOCKING_PERIOD_PRESET = VariablePeriod.THREE_MONTHS;
	public static final RandomizationMode TRIAL_RANDOMIZATION_PRESET = RandomizationMode.GROUP_COIN;
	public static final String TRIAL_RANDOMIZATION_LIST_PRESET = "";
	public static final String STRATIFICATION_RANDOMIZATION_LIST_RANDOMIZATION_LIST_PRESET = "";
	public static final int GENERATE_RANDOMIZATION_LIST_N_PRESET = 100;
	public static final Long TRIAL_BLOCKING_PERIOD_DAYS_PRESET = null;
	public static final boolean PROBAND_LIST_BULK_ADD_SHUFFLE = true;
	public static final boolean PROBAND_LIST_BULK_ADD_RANDOMIZE = false;
	public static final Long PROBAND_LIST_BULK_ADD_LIMIT = null;
	public static final VariablePeriod TIMELINE_RANGE_START_PERIOD_BEFORE = VariablePeriod.THREE_MONTHS;
	public static final Long TIMELINE_RANGE_START_PERIOD_BEFORE_DAYS = null;
	public static final VariablePeriod TIMELINE_RANGE_START_PERIOD_AFTER = VariablePeriod.THREE_MONTHS;
	public static final Long TIMELINE_RANGE_START_PERIOD_AFTER_DAYS = null;
	public static final boolean TIMELINE_SHOW_TIMELINE_EVENTS_PRESET = true;
	public static final boolean TIMELINE_SHOW_VISIT_SCHEDULE_ITEMS_PRESET = false;
	public static final boolean LIMIT_JOURNAL_ENTRY_USERS = false;
	public static final boolean LOAD_JOURNAL_ENTRY_USERS = false;
	public static final boolean LIMIT_JOURNAL_ENTRY_TAG_CLOUD = true;
	public static final boolean LIMIT_JOURNAL_ENTRY_RECENT = true;
	public static final boolean ENABLE_RECENT_ENTITIES_MENU = false;
	public static final Color DUTY_SELF_ALLOCATION_LOCKED_COLOR = Color.GAINSBORO;
	public static final ArrayList<String> INVENTORY_BOOKING_SCHEDULE_TRIAL_COLORS = new ArrayList<String>();
	public static final Long MAX_COST_TYPES_PER_TRIAL = 10l;
	public static final Long MAX_COST_TYPES_COLUMNS = 5l;
	public final static Color ENROLLMENT_STATUS_IS_NOT_COUNT_COLOR = Color.GAINSBORO;
	public final static PaymentMethod PAYOFF_PAYMENT_METHOD = null;
	public final static boolean ENABLE_GEOLOCATION_SERVICES = false;
	public final static boolean FORCE_DEFAULT_GEOLOCATION = false;
	public final static boolean HIGHLIGHT_TEXT_INPUT = false;
	public static final float DEFAULT_GEOLOCATION_LATITUDE = 47.081424f;
	public static final float DEFAULT_GEOLOCATION_LONGITUDE = 15.468107f;
	public static final String GOOGLE_API_URL = "https://maps.google.at/maps/api/js?sensor=false";
	public static final Integer INPUT_FIELD_DELTA_SUMMARY_MAX = 100;
	public static final int FIELD_CALCULATION_DEBUG_LEVEL = 0;
	public static final String PRIVATE_CAPTCHA_KEY = "";
	public static final String PUBLIC_CAPTCHA_KEY = "";
	public static final boolean PROBAND_GROUPS_SHOW_INQUIRY_COLUMN = false;
	public static final boolean PROBAND_GROUPS_SHOW_PROBAND_LIST_ENTRY_TAG_COLUMN = true;
	public static final boolean PROBAND_LIST_SHOW_INQUIRY_COLUMN = true;
	public static final boolean PROBAND_LIST_SHOW_PROBAND_LIST_ENTRY_TAG_COLUMN = true;
	public static final boolean TRIAL_PARTICIPATIONS_SHOW_INQUIRY_COLUMN = true;
	public static final boolean TRIAL_PARTICIPATIONS_SHOW_PROBAND_LIST_ENTRY_TAG_COLUMN = true;
	public static final boolean TRIAL_ECRF_DATA_ENTRIES_SHOW_INQUIRY_COLUMN = true;
	public static final boolean TRIAL_ECRF_DATA_ENTRIES_SHOW_PROBAND_LIST_ENTRY_TAG_COLUMN = true;
	public static final boolean PROBAND_ECRF_DATA_ENTRIES_SHOW_INQUIRY_COLUMN = true;
	public static final boolean PROBAND_ECRF_DATA_ENTRIES_SHOW_PROBAND_LIST_ENTRY_TAG_COLUMN = true;
	public static final boolean SHOW_COURSE_SCHEDULE_EVENT_ICONS = true;
	public static final boolean SHOW_DUTY_ROSTER_TURN_SCHEDULE_EVENT_ICONS = true;
	public static final boolean SHOW_INVENTORY_BOOKING_SCHEDULE_EVENT_ICONS = true;
	public static final boolean SHOW_TIMELINE_EVENT_SCHEDULE_EVENT_ICONS = true;
	public static final int GROUP_VISIT_MATRIX_DEFAULT_PAGE_SIZE = 100;
	public static final Color GROUP_VISIT_MATRIX_NO_VISIT_COLOR = null;
	public static final Color GROUP_VISIT_MATRIX_GAP_COLOR = Color.CORNFLOWERBLUE;
	public static final Color GROUP_VISIT_MATRIX_NOT_LOADED_COLOR = Color.GAINSBORO;
	public static final boolean PROBAND_MONEY_TRANSFER_SUMMARY_SHOW_ALL_PROBAND_LIST_ENTRIES = true;
	public static final boolean GROUP_VISIT_MATRIX_VISITS_VERTICAL_DEFAULT = false;
	public static final boolean COURSE_DEFERRED_DELETE = true;
	public static final boolean ECRF_DEFERRED_DELETE = false;
	public static final boolean ECRF_FIELD_DEFERRED_DELETE = false;
	public static final boolean INPUT_FIELD_DEFERRED_DELETE = false;
	public static final boolean INQUIRY_DEFERRED_DELETE = false;
	public static final boolean INVENTORY_DEFERRED_DELETE = true;
	public static final boolean PROBAND_DEFERRED_DELETE = true;
	public static final boolean CRITERIA_DEFERRED_DELETE = false;
	public static final boolean SELECTION_SET_VALUE_DEFERRED_DELETE = false;
	public static final boolean STAFF_DEFERRED_DELETE = true;
	public static final boolean TRIAL_DEFERRED_DELETE = true;
	public static final boolean USER_DEFERRED_DELETE = false;
	public static final boolean MASS_MAIL_DEFERRED_DELETE = true;
	public static final int PROGRESS_BAR_MAX_VALUE = 100;
	public static final boolean ENABLE_PROBAND_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_STAFF_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_PROBAND_LIST_EXPORTS = false;
	public static final boolean ENABLE_INVENTORY_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_COURSE_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_TRIAL_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_INPUT_FIELD_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_USER_SEARCH_EXPORTS = false;
	public static final boolean ENABLE_JOURNAL_EXPORTS = false;
	public static final boolean ENABLE_MASS_MAIL_SEARCH_EXPORTS = false;
	public static final int TIME_PICKER_INTERVAL_MINUTES = 5;
	public static final Float MEDICATION_DOSE_VALUE_PRESET = null;
	public static final boolean VISIT_SCHEDULE_ITEM_NOTIFY_PRESET = false;
	public static final boolean PROBAND_PERSON_PRESET = true;
	public static final boolean PROBAND_BLINDED_PRESET = false;
	public static final ECRFFieldStatusQueue ECRF_FIELD_STATUS_QUEUE = null;
	public static final boolean SHOW_ECRF_STATUS_ECRF_LOG = false;
	public static final boolean SHOW_LAST_UNRESOLVED_FIELD_STATUS = true;
	public static final boolean ECRF_CLONE_ADD_OTHER_TRIAL_ENABLED = false;
	public static final boolean ADD_REIMBURSEMENT_SHOW_COMMENT = true;
	public static final float ADD_REIMBURSEMENT_TRAVEL_EXPENSES_FACTOR = 0.5f;
	public static final String ADD_REIMBURSEMENT_COMMENT_DATE_PATTERN = "yyyy-MM-dd";
	public static final int ADD_REIMBURSEMENT_COMMENT_CLIP_MAX_LENGTH = 30;
	public static final boolean ENABLE_INVENTORY_MODULE = false;
	public static final boolean ENABLE_STAFF_MODULE = false;
	public static final boolean ENABLE_COURSE_MODULE = false;
	public static final boolean ENABLE_TRIAL_MODULE = false;
	public static final boolean ENABLE_PROBAND_MODULE = false;
	public static final boolean ENABLE_INPUT_FIELD_MODULE = false;
	public static final boolean ENABLE_USER_MODULE = false;
	public static final boolean ENABLE_MASS_MAIL_MODULE = false;
	public static final Long PROBAND_RATING_PRESET = null;
	public static final Long PROBAND_RATING_MAX_PRESET = null;
	public static final boolean SHOW_PROBAND_RATING = false;
	public static final Long PROBAND_LIST_ENTRY_RATING_PRESET = null;
	public static final Long PROBAND_LIST_ENTRY_RATING_MAX_PRESET = null;
	public static final boolean SHOW_PROBAND_LIST_ENTRY_RATING = false;
	public static final Long DUTY_ROSTER_SCHEDULE_STAFF_NA_COUNT_LIMIT = null;
	public static final boolean MASS_MAIL_LOCK_AFTER_SENDING_PRESET = false;
	public static final String MASS_MAIL_FROM_ADDRESS_PRESET = "";
	public static final String MASS_MAIL_FROM_NAME_PRESET = "";
	public static final String MASS_MAIL_REPLY_TO_ADDRESS_PRESET = "";
	public static final String MASS_MAIL_REPLY_TO_NAME_PRESET = "";
	public static final boolean MASS_MAIL_PROBAND_TO_PRESET = true;
	public static final boolean MASS_MAIL_PHYSICIAN_TO_PRESET = false;
	public static final String MASS_MAIL_OTHER_TO_PRESET = "";
	public static final String MASS_MAIL_CC_PRESET = "";
	public static final String MASS_MAIL_BCC_PRESET = "";
	public static final boolean MASS_MAIL_USE_BEACON_PRESET = false;
	public static final boolean MASS_MAIL_ATTACH_MASS_MAIL_FILES_PRESET = false;
	public static final String MASS_MAIL_MASS_MAIL_FILES_LOGICAL_PATH_PRESET = "";
	public static final boolean MASS_MAIL_ATTACH_TRIAL_FILES_PRESET = false;
	public static final String MASS_MAIL_TRIAL_FILES_LOGICAL_PATH_PRESET = "";
	public static final boolean MASS_MAIL_ATTACH_PROBAND_FILES_PRESET = false;
	public static final String MASS_MAIL_PROBAND_LOGICAL_PATH_PRESET = "";
	public static final boolean MASS_MAIL_ATTACH_INQUIRIES_PRESET = false;
	public static final boolean MASS_MAIL_ATTACH_PROBAND_LIST_ENTRY_TAGS_PRESET = false;
	public static final boolean MASS_MAIL_ATTACH_ECRFS_PRESET = false;
	public static final boolean MASS_MAIL_ATTACH_PROBAND_LETTER_PRESET = false;
	public static final boolean MASS_MAIL_ATTACH_REIMBURSEMENTS_PRESET = false;
	public static final String MASS_MAIL_LOCALE_PRESET = CommonUtil.localeToString(Locale.getDefault());
	public static final String PUBLIC_FILE_SIGNUP_URL = null;
	public static final Boolean RECIPIENT_OVERVIEW_SHOW_PENDING_PRESET = null;
	public static final boolean RECIPIENT_OVERVIEW_SHOW_SCHEDULED_PRESET = true;
	public static final boolean MASS_MAIL_PROBAND_LIST_STATUS_RESEND_PRESET = false;
	public static final boolean MASS_MAIL_TRIAL_TEAM_TO_PRESET = false;
	public static final boolean PROBAND_ADDRESS_STRICT = false;
	public static final boolean STAFF_ADDRESS_STRICT = false;
	public static final boolean SHOW_LOCALE_MENU = false;
	public static final boolean SHOW_TIMEZONE_MENU = false;
	public static final boolean SHOW_THEME_MENU = false;
	public static final boolean SHOW_TOOLTIPS_MENU = false;
	public static final boolean USER_ENABLE_INVENTORY_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_STAFF_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_COURSE_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_TRIAL_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_INPUT_FIELD_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_PROBAND_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_MASS_MAIL_MODULE_PRESET = true;
	public static final boolean USER_ENABLE_USER_MODULE_PRESET = true;

	private DefaultSettings() {
	}
}
