package org.phoenixctms.ctsms.excel;

import java.util.ArrayList;

public final class JournalExcelDefaultSettings {

	public static final int VO_GRAPH_RECURSION_DEPTH = 1; // 2 very slow!
	public static final String INVENTORY_TEMPLATE_FILE_NAME = null;
	public static final boolean INVENTORY_AUTOSIZE = true;
	public static final boolean INVENTORY_WRITEHEAD = true;
	public static final Integer INVENTORY_PAGE_BREAK_AT_ROW = null;
	public static final String STAFF_TEMPLATE_FILE_NAME = null;
	public static final boolean STAFF_AUTOSIZE = true;
	public static final boolean STAFF_WRITEHEAD = true;
	public static final Integer STAFF_PAGE_BREAK_AT_ROW = null;
	public static final String COURSE_TEMPLATE_FILE_NAME = null;
	public static final boolean COURSE_AUTOSIZE = true;
	public static final boolean COURSE_WRITEHEAD = true;
	public static final Integer COURSE_PAGE_BREAK_AT_ROW = null;
	public static final String TRIAL_TEMPLATE_FILE_NAME = null;
	public static final boolean TRIAL_AUTOSIZE = true;
	public static final boolean TRIAL_WRITEHEAD = true;
	public static final Integer TRIAL_PAGE_BREAK_AT_ROW = null;
	public static final String PROBAND_TEMPLATE_FILE_NAME = null;
	public static final boolean PROBAND_AUTOSIZE = true;
	public static final boolean PROBAND_WRITEHEAD = true;
	public static final Integer PROBAND_PAGE_BREAK_AT_ROW = null;
	public static final String USER_TEMPLATE_FILE_NAME = null;
	public static final boolean USER_AUTOSIZE = true;
	public static final boolean USER_WRITEHEAD = true;
	public static final Integer USER_PAGE_BREAK_AT_ROW = null;
	public static final String INPUT_FIELD_TEMPLATE_FILE_NAME = null;
	public static final boolean INPUT_FIELD_AUTOSIZE = true;
	public static final boolean INPUT_FIELD_WRITEHEAD = true;
	public static final Integer INPUT_FIELD_PAGE_BREAK_AT_ROW = null;
	public static final String CRITERIA_TEMPLATE_FILE_NAME = null;
	public static final boolean CRITERIA_AUTOSIZE = true;
	public static final boolean CRITERIA_WRITEHEAD = true;
	public static final Integer CRITERIA_PAGE_BREAK_AT_ROW = null;
	public static final String ECRF_TEMPLATE_FILE_NAME = null;
	public static final boolean ECRF_AUTOSIZE = true;
	public static final boolean ECRF_WRITEHEAD = true;
	public static final Integer ECRF_PAGE_BREAK_AT_ROW = null;
	public static final String MASS_MAIL_TEMPLATE_FILE_NAME = null;
	public static final boolean MASS_MAIL_AUTOSIZE = true;
	public static final boolean MASS_MAIL_WRITEHEAD = true;
	public static final Integer MASS_MAIL_PAGE_BREAK_AT_ROW = null;
	public static final String INVENTORY_SPREADSHEET_NAME = null;
	public static final String STAFF_SPREADSHEET_NAME = null;
	public static final String COURSE_SPREADSHEET_NAME = null;
	public static final String TRIAL_SPREADSHEET_NAME = null;
	public static final String PROBAND_SPREADSHEET_NAME = null;
	public static final String USER_SPREADSHEET_NAME = null;
	public static final String INPUT_FIELD_SPREADSHEET_NAME = null;
	public static final String CRITERIA_SPREADSHEET_NAME = null;
	public static final String ECRF_SPREADSHEET_NAME = null;
	public static final String MASS_MAIL_SPREADSHEET_NAME = null;
	public static final Integer INVENTORY_SCALE_FACTOR = null;
	public static final Integer STAFF_SCALE_FACTOR = null;
	public static final Integer COURSE_SCALE_FACTOR = null;
	public static final Integer TRIAL_SCALE_FACTOR = null;
	public static final Integer PROBAND_SCALE_FACTOR = null;
	public static final Integer USER_SCALE_FACTOR = null;
	public static final Integer INPUT_FIELD_SCALE_FACTOR = null;
	public static final Integer CRITERIA_SCALE_FACTOR = null;
	public static final Integer ECRF_SCALE_FACTOR = null;
	public static final Integer MASS_MAIL_SCALE_FACTOR = null;
	public static final ExcelCellFormat INVENTORY_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat STAFF_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat COURSE_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat TRIAL_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat PROBAND_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat USER_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat INPUT_FIELD_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat CRITERIA_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat ECRF_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat MASS_MAIL_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat INVENTORY_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat STAFF_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat COURSE_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat TRIAL_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat PROBAND_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat USER_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat INPUT_FIELD_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat CRITERIA_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat ECRF_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat MASS_MAIL_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final boolean INVENTORY_ROW_COLORS = true;
	public static final boolean STAFF_ROW_COLORS = true;
	public static final boolean COURSE_ROW_COLORS = true;
	public static final boolean TRIAL_ROW_COLORS = true;
	public static final boolean PROBAND_ROW_COLORS = true;
	public static final boolean USER_ROW_COLORS = true;
	public static final boolean INPUT_FIELD_ROW_COLORS = true;
	public static final boolean CRITERIA_ROW_COLORS = true;
	public static final boolean ECRF_ROW_COLORS = true;
	public static final boolean MASS_MAIL_ROW_COLORS = true;
	public static final ArrayList<String> INVENTORY_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> STAFF_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> COURSE_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> TRIAL_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> PROBAND_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> USER_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> CRITERIA_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> INPUT_FIELD_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> ECRF_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final ArrayList<String> MASS_MAIL_VO_FIELD_COLUMNS = new ArrayList<String>();
	public static final String PAINTER_CLASS = null;
	public static final ArrayList<String> PAINTER_SOURCE_FILES = null;
	static {
		INVENTORY_VO_FIELD_COLUMNS.add("id");
		INVENTORY_VO_FIELD_COLUMNS.add("systemMessage");
		INVENTORY_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INVENTORY_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		INVENTORY_VO_FIELD_COLUMNS.add("realTimestamp");
		INVENTORY_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INVENTORY_VO_FIELD_COLUMNS.add("title");
		INVENTORY_VO_FIELD_COLUMNS.add("comment");
		STAFF_VO_FIELD_COLUMNS.add("id");
		STAFF_VO_FIELD_COLUMNS.add("systemMessage");
		STAFF_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		STAFF_VO_FIELD_COLUMNS.add("realTimestamp");
		STAFF_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("title");
		STAFF_VO_FIELD_COLUMNS.add("comment");
		COURSE_VO_FIELD_COLUMNS.add("id");
		COURSE_VO_FIELD_COLUMNS.add("systemMessage");
		COURSE_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		COURSE_VO_FIELD_COLUMNS.add("realTimestamp");
		COURSE_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("title");
		COURSE_VO_FIELD_COLUMNS.add("comment");
		TRIAL_VO_FIELD_COLUMNS.add("id");
		TRIAL_VO_FIELD_COLUMNS.add("systemMessage");
		TRIAL_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		TRIAL_VO_FIELD_COLUMNS.add("realTimestamp");
		TRIAL_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("title");
		TRIAL_VO_FIELD_COLUMNS.add("comment");
		PROBAND_VO_FIELD_COLUMNS.add("id");
		PROBAND_VO_FIELD_COLUMNS.add("systemMessage");
		PROBAND_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		PROBAND_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		PROBAND_VO_FIELD_COLUMNS.add("realTimestamp");
		PROBAND_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		PROBAND_VO_FIELD_COLUMNS.add("title");
		PROBAND_VO_FIELD_COLUMNS.add("comment");
		USER_VO_FIELD_COLUMNS.add("id");
		USER_VO_FIELD_COLUMNS.add("systemMessage");
		USER_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		USER_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		USER_VO_FIELD_COLUMNS.add("realTimestamp");
		USER_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		USER_VO_FIELD_COLUMNS.add("title");
		USER_VO_FIELD_COLUMNS.add("comment");
		CRITERIA_VO_FIELD_COLUMNS.add("id");
		CRITERIA_VO_FIELD_COLUMNS.add("systemMessage");
		CRITERIA_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		CRITERIA_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		CRITERIA_VO_FIELD_COLUMNS.add("realTimestamp");
		CRITERIA_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		CRITERIA_VO_FIELD_COLUMNS.add("title");
		CRITERIA_VO_FIELD_COLUMNS.add("comment");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("id");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("systemMessage");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("realTimestamp");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("title");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("comment");
		ECRF_VO_FIELD_COLUMNS.add("id");
		ECRF_VO_FIELD_COLUMNS.add("systemMessage");
		ECRF_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		ECRF_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		ECRF_VO_FIELD_COLUMNS.add("realTimestamp");
		ECRF_VO_FIELD_COLUMNS.add("inputField" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		ECRF_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		ECRF_VO_FIELD_COLUMNS.add("title");
		ECRF_VO_FIELD_COLUMNS.add("comment");
		MASS_MAIL_VO_FIELD_COLUMNS.add("id");
		MASS_MAIL_VO_FIELD_COLUMNS.add("systemMessage");
		MASS_MAIL_VO_FIELD_COLUMNS.add("modifiedUser" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		MASS_MAIL_VO_FIELD_COLUMNS.add("modifiedTimestamp");
		MASS_MAIL_VO_FIELD_COLUMNS.add("realTimestamp");
		MASS_MAIL_VO_FIELD_COLUMNS.add("inputField" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		MASS_MAIL_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		MASS_MAIL_VO_FIELD_COLUMNS.add("title");
		MASS_MAIL_VO_FIELD_COLUMNS.add("comment");
	}

	private JournalExcelDefaultSettings() {
	}
}
