package org.phoenixctms.ctsms.excel;

public interface ReimbursementsExcelSettingCodes {

	public static final String VO_GRAPH_RECURSION_DEPTH = "vo_graph_recursion_depth";
	public static final String TEMPLATE_FILE_NAME = "template_file_name";
	public static final String AUTOSIZE = "autosize";
	public static final String WRITEHEAD = "writehead";
	public static final String PAGE_BREAK_AT_ROW = "page_break_at_row";
	public static final String SCALE_FACTOR = "scale_factor";
	public static final String HEAD_FORMAT = "head_format";
	public static final String ROW_FORMAT = "row_format";
	public static final String ROW_COLORS = "row_colors";
	public static final String APPEND_HEADER_FOOTER = "append_header_footer";
	public static final String SHOW_ADDRESSES = "show_addresses";
	public static final String AGGREGATE_ADDRESSES = "aggregate_addresses";
	public static final String PETTY_CASH_TEMPLATE_FILE_NAME = "petty_cash_template_file_name";
	public static final String PETTY_CASH_AUTOSIZE = "petty_cash_autosize";
	public static final String PETTY_CASH_WRITEHEAD = "petty_cash_writehead";
	public static final String PETTY_CASH_PAGE_BREAK_AT_ROW = "petty_cash_page_break_at_row";
	public static final String PETTY_CASH_SCALE_FACTOR = "petty_cash_scale_factor";
	public static final String PETTY_CASH_HEAD_FORMAT = "petty_cash_head_format";
	public static final String PETTY_CASH_ROW_FORMAT = "petty_cash_row_format";
	public static final String PETTY_CASH_ROW_COLORS = "petty_cash_row_colors";
	public static final String PETTY_CASH_APPEND_HEADER_FOOTER = "petty_cash_append_header_footer";
	public static final String PETTY_CASH_SHOW_ADDRESSES = "petty_cash_show_addresses";
	public static final String PETTY_CASH_AGGREGATE_ADDRESSES = "petty_cash_aggregate_addresses";
	public static final String VOUCHER_TEMPLATE_FILE_NAME = "voucher_template_file_name";
	public static final String VOUCHER_AUTOSIZE = "voucher_autosize";
	public static final String VOUCHER_WRITEHEAD = "voucher_writehead";
	public static final String VOUCHER_PAGE_BREAK_AT_ROW = "voucher_page_break_at_row";
	public static final String VOUCHER_SCALE_FACTOR = "voucher_scale_factor";
	public static final String VOUCHER_HEAD_FORMAT = "voucher_head_format";
	public static final String VOUCHER_ROW_FORMAT = "voucher_row_format";
	public static final String VOUCHER_ROW_COLORS = "voucher_row_colors";
	public static final String VOUCHER_APPEND_HEADER_FOOTER = "voucher_append_header_footer";
	public static final String VOUCHER_SHOW_ADDRESSES = "voucher_show_addresses";
	public static final String VOUCHER_AGGREGATE_ADDRESSES = "voucher_aggregate_addresses";
	public static final String WIRE_TRANSFER_TEMPLATE_FILE_NAME = "wire_transfer_template_file_name";
	public static final String WIRE_TRANSFER_AUTOSIZE = "wire_transfer_autosize";
	public static final String WIRE_TRANSFER_WRITEHEAD = "wire_transfer_writehead";
	public static final String WIRE_TRANSFER_PAGE_BREAK_AT_ROW = "wire_transfer_page_break_at_row";
	public static final String WIRE_TRANSFER_SCALE_FACTOR = "wire_transfer_scale_factor";
	public static final String WIRE_TRANSFER_HEAD_FORMAT = "wire_transfer_head_format";
	public static final String WIRE_TRANSFER_ROW_FORMAT = "wire_transfer_row_format";
	public static final String WIRE_TRANSFER_ROW_COLORS = "wire_transfer_row_colors";
	public static final String WIRE_TRANSFER_APPEND_HEADER_FOOTER = "wire_transfer_append_header_footer";
	public static final String WIRE_TRANSFER_SHOW_ADDRESSES = "wire_transfer_show_addresses";
	public static final String WIRE_TRANSFER_AGGREGATE_ADDRESSES = "wire_transfer_aggregate_addresses";
	public static final String PAINTER_CLASS = "painter_class";
	public static final String PAINTER_SOURCE_FILES = "painter_source_files";
}
