package org.phoenixctms.ctsms.excel;

import java.util.ArrayList;

public final class SearchResultExcelDefaultSettings {

	public static final int VO_GRAPH_RECURSION_DEPTH = 1;
	public static final String INVENTORY_TEMPLATE_FILE_NAME = null;
	public static final boolean INVENTORY_WRITEHEAD = true;
	public static final boolean INVENTORY_AUTOSIZE = true;
	public static final Integer INVENTORY_PAGE_BREAK_AT_ROW = null;
	public static final String STAFF_TEMPLATE_FILE_NAME = null;
	public static final boolean STAFF_WRITEHEAD = true;
	public static final boolean STAFF_AUTOSIZE = true;
	public static final Integer STAFF_PAGE_BREAK_AT_ROW = null;
	public static final String COURSE_TEMPLATE_FILE_NAME = null;
	public static final boolean COURSE_WRITEHEAD = true;
	public static final boolean COURSE_AUTOSIZE = true;
	public static final Integer COURSE_PAGE_BREAK_AT_ROW = null;
	public static final String TRIAL_TEMPLATE_FILE_NAME = null;
	public static final boolean TRIAL_WRITEHEAD = true;
	public static final boolean TRIAL_AUTOSIZE = true;
	public static final Integer TRIAL_PAGE_BREAK_AT_ROW = null;
	public static final String PROBAND_TEMPLATE_FILE_NAME = null;
	public static final boolean PROBAND_WRITEHEAD = true;
	public static final boolean PROBAND_AUTOSIZE = true;
	public static final Integer PROBAND_PAGE_BREAK_AT_ROW = null;
	public static final String USER_TEMPLATE_FILE_NAME = null;
	public static final boolean USER_WRITEHEAD = true;
	public static final boolean USER_AUTOSIZE = true;
	public static final Integer USER_PAGE_BREAK_AT_ROW = null;
	public static final String INPUT_FIELD_TEMPLATE_FILE_NAME = null;
	public static final boolean INPUT_FIELD_WRITEHEAD = true;
	public static final boolean INPUT_FIELD_AUTOSIZE = true;
	public static final Integer INPUT_FIELD_PAGE_BREAK_AT_ROW = null;
	public static final String INVENTORY_SPREADSHEET_NAME = null;
	public static final String STAFF_SPREADSHEET_NAME = null;
	public static final String COURSE_SPREADSHEET_NAME = null;
	public static final String TRIAL_SPREADSHEET_NAME = null;
	public static final String PROBAND_SPREADSHEET_NAME = null;
	public static final String USER_SPREADSHEET_NAME = null;
	public static final String INPUT_FIELD_SPREADSHEET_NAME = null;
	public static final Integer INVENTORY_SCALE_FACTOR = null;
	public static final Integer STAFF_SCALE_FACTOR = null;
	public static final Integer COURSE_SCALE_FACTOR = null;
	public static final Integer TRIAL_SCALE_FACTOR = null;
	public static final Integer PROBAND_SCALE_FACTOR = null;
	public static final Integer USER_SCALE_FACTOR = null;
	public static final Integer INPUT_FIELD_SCALE_FACTOR = null;
	public static final ExcelCellFormat INVENTORY_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat STAFF_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat COURSE_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat TRIAL_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat PROBAND_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat USER_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat INPUT_FIELD_HEAD_FORMAT = ExcelCellFormat.getDefaultHeadFormat();
	public static final ExcelCellFormat INVENTORY_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat STAFF_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat COURSE_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat TRIAL_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat PROBAND_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat USER_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final ExcelCellFormat INPUT_FIELD_ROW_FORMAT = ExcelCellFormat.getDefaultRowFormat();
	public static final boolean INVENTORY_ROW_COLORS = true;
	public static final boolean STAFF_ROW_COLORS = true;
	public static final boolean COURSE_ROW_COLORS = true;
	public static final boolean TRIAL_ROW_COLORS = true;
	public static final boolean PROBAND_ROW_COLORS = true;
	public static final boolean USER_ROW_COLORS = true;
	public static final boolean INPUT_FIELD_ROW_COLORS = true;
	public final static ArrayList<String> INVENTORY_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> STAFF_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> COURSE_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> TRIAL_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> INPUT_FIELD_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> PROBAND_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static ArrayList<String> USER_VO_FIELD_COLUMNS = new ArrayList<String>();
	public final static int GRAPH_MAX_COURSE_INSTANCES = 1;
	public final static int GRAPH_MAX_STAFF_INSTANCES = 2;
	public final static int GRAPH_MAX_INVENTORY_INSTANCES = 2;
	public final static int GRAPH_MAX_USER_INSTANCES = 1;
	public final static int GRAPH_MAX_PROBAND_INSTANCES = 1;
	public static final boolean SHOW_INVENTORY_TAGS = true;
	public static final boolean SHOW_STAFF_TAGS = true;
	public static final boolean SHOW_TRIAL_TAGS = true;
	public static final boolean SHOW_TEAM_MEMBERS = true;
	public static final boolean SHOW_TIMELINE_EVENTS = true;
	public static final Boolean SHOW_PROBAND_PERSON_COLUMNS = null;
	public static final Boolean SHOW_PROBAND_ANIMAL_COLUMNS = null;
	public static final boolean SHOW_PROBAND_TAGS = false;
	public static final boolean SHOW_PROBAND_CONTACT_DETAILS = true;
	public static final boolean SHOW_PROBAND_ADDRESSES = true;
	public static final boolean SHOW_INQUIRIES = false;
	public static final boolean SHOW_ALL_INQUIRIES = false;
	public static final boolean SHOW_ALL_INQUIRY_DATES = false;
	public static final boolean SHOW_EMPTY_INQUIRY_COLUMNS = false;
	static {
		INVENTORY_VO_FIELD_COLUMNS.add("id");
		INVENTORY_VO_FIELD_COLUMNS.add("deferredDelete");
		INVENTORY_VO_FIELD_COLUMNS.add("name");
		INVENTORY_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INVENTORY_VO_FIELD_COLUMNS.add("bookable");
		INVENTORY_VO_FIELD_COLUMNS.add("pieces");
		INVENTORY_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INVENTORY_VO_FIELD_COLUMNS.add("parent" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "id");
		INVENTORY_VO_FIELD_COLUMNS.add("parent" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INVENTORY_VO_FIELD_COLUMNS.add("owner" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "id");
		INVENTORY_VO_FIELD_COLUMNS.add("owner" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("id");
		STAFF_VO_FIELD_COLUMNS.add("deferredDelete");
		STAFF_VO_FIELD_COLUMNS.add("person");
		STAFF_VO_FIELD_COLUMNS.add("name");
		STAFF_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("allocatable");
		STAFF_VO_FIELD_COLUMNS.add("employee");
		STAFF_VO_FIELD_COLUMNS.add("dateOfBirth");
		STAFF_VO_FIELD_COLUMNS.add("gender" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		STAFF_VO_FIELD_COLUMNS.add("parent" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "id");
		STAFF_VO_FIELD_COLUMNS.add("parent" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("id");
		COURSE_VO_FIELD_COLUMNS.add("deferredDelete");
		COURSE_VO_FIELD_COLUMNS.add("name");
		COURSE_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("cvTitle");
		COURSE_VO_FIELD_COLUMNS.add("cvSectionPreset" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("description");
		COURSE_VO_FIELD_COLUMNS.add("start");
		COURSE_VO_FIELD_COLUMNS.add("stop");
		COURSE_VO_FIELD_COLUMNS.add("selfRegistration");
		COURSE_VO_FIELD_COLUMNS.add("participationDeadline");
		COURSE_VO_FIELD_COLUMNS.add("maxNumberOfParticipants");
		COURSE_VO_FIELD_COLUMNS.add("expires");
		COURSE_VO_FIELD_COLUMNS.add("validityPeriod" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("validityPeriodDays");
		COURSE_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		COURSE_VO_FIELD_COLUMNS.add("institution" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "id");
		COURSE_VO_FIELD_COLUMNS.add("institution" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("id");
		TRIAL_VO_FIELD_COLUMNS.add("deferredDelete");
		TRIAL_VO_FIELD_COLUMNS.add("name");
		TRIAL_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("title");
		TRIAL_VO_FIELD_COLUMNS.add("description");
		TRIAL_VO_FIELD_COLUMNS.add("type" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("sponsoring" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("surveyStatus" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("status" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("dutySelfAllocationLocked");
		TRIAL_VO_FIELD_COLUMNS.add("dutySelfAllocationLockedUntil");
		TRIAL_VO_FIELD_COLUMNS.add("dutySelfAllocationLockedFrom");
		TRIAL_VO_FIELD_COLUMNS.add("exclusiveProbands");
		TRIAL_VO_FIELD_COLUMNS.add("blockingPeriod" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		TRIAL_VO_FIELD_COLUMNS.add("blockingPeriodDays");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("id");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("deferredDelete");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("name");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("fieldType" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("title");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("category");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("comment");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("textPreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("regExp");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("longPreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("longLowerLimit");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("longUpperLimit");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("floatPreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("floatLowerLimit");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("floatUpperLimit");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("datePreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("minDate");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("maxDate");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("timestampPreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("minTimestamp");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("maxTimestamp");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("booleanPreset");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("minSelections");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("maxSelections");
		INPUT_FIELD_VO_FIELD_COLUMNS.add("validationErrorMsg");
		USER_VO_FIELD_COLUMNS.add("id");
		USER_VO_FIELD_COLUMNS.add("deferredDelete");
		USER_VO_FIELD_COLUMNS.add("name");
		USER_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		USER_VO_FIELD_COLUMNS.add("locked");
		USER_VO_FIELD_COLUMNS.add("authMethod" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		USER_VO_FIELD_COLUMNS.add("locale");
		USER_VO_FIELD_COLUMNS.add("timeZone");
		USER_VO_FIELD_COLUMNS.add("theme");
		USER_VO_FIELD_COLUMNS.add("identity" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		USER_VO_FIELD_COLUMNS.add("identity" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "id");
		PROBAND_VO_FIELD_COLUMNS.add("id");
		PROBAND_VO_FIELD_COLUMNS.add("deferredDelete");
		PROBAND_VO_FIELD_COLUMNS.add("firstName");
		PROBAND_VO_FIELD_COLUMNS.add("lastName");
		PROBAND_VO_FIELD_COLUMNS.add("animalName");
		PROBAND_VO_FIELD_COLUMNS.add("department" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		// PROBAND_VO_FIELD_COLUMNS.add("available");
		// PROBAND_VO_FIELD_COLUMNS.add("recruitmentForOtherTrialsAllowed");
		PROBAND_VO_FIELD_COLUMNS.add("citizenship");
		PROBAND_VO_FIELD_COLUMNS.add("dateOfBirth");
		PROBAND_VO_FIELD_COLUMNS.add("age");
		PROBAND_VO_FIELD_COLUMNS.add("gender" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		PROBAND_VO_FIELD_COLUMNS.add("category" + ExcelUtil.COLUMN_NAME_ASSOCIATION_PATH_SEPARATOR + "name");
		PROBAND_VO_FIELD_COLUMNS.add("comment");
		// PROBAND_VO_FIELD_COLUMNS.add("autoDelete");
		// PROBAND_VO_FIELD_COLUMNS.add("autoDeleteDeadline");
	}

	private SearchResultExcelDefaultSettings() {
	}
}
