
alter table COURSE add column SHOW_COMMENT_TRAINING_RECORD_PRESET BOOLEAN;
update COURSE set SHOW_COMMENT_TRAINING_RECORD_PRESET = 'f';
alter table COURSE alter SHOW_COMMENT_TRAINING_RECORD_PRESET set not null;

alter table COURSE_PARTICIPATION_STATUS_ENTRY add column SHOW_COMMENT_TRAINING_RECORD BOOLEAN;
update COURSE_PARTICIPATION_STATUS_ENTRY set SHOW_COMMENT_TRAINING_RECORD = 'f';
alter table COURSE_PARTICIPATION_STATUS_ENTRY alter SHOW_COMMENT_TRAINING_RECORD set not null;


alter table TRIAL_STATUS_TYPE add column RELEVANT_FOR_COURSES BOOLEAN;
update TRIAL_STATUS_TYPE set RELEVANT_FOR_COURSES = 't';
update TRIAL_STATUS_TYPE set RELEVANT_FOR_COURSES = 'f' where NAME_L10N_KEY = 'cancelled';
update TRIAL_STATUS_TYPE set RELEVANT_FOR_COURSES = 'f' where NAME_L10N_KEY = 'lockdown';
update TRIAL_STATUS_TYPE set RELEVANT_FOR_COURSES = 'f' where NAME_L10N_KEY = 'migrated';
alter table TRIAL_STATUS_TYPE alter RELEVANT_FOR_COURSES set not null;

alter table COURSE_PARTICIPATION_STATUS_TYPE add column FILE_REQUIRED BOOLEAN;
update COURSE_PARTICIPATION_STATUS_TYPE set FILE_REQUIRED = 'f';
alter table COURSE_PARTICIPATION_STATUS_TYPE alter FILE_REQUIRED set not null;