
alter table COURSE add column SHOW_COMMENT_TRAINING_RECORD_PRESET BOOLEAN;
update COURSE set SHOW_COMMENT_TRAINING_RECORD_PRESET = 'f';
alter table COURSE alter SHOW_COMMENT_TRAINING_RECORD_PRESET set not null;

alter table COURSE_PARTICIPATION_STATUS_ENTRY add column SHOW_COMMENT_TRAINING_RECORD BOOLEAN;
update COURSE_PARTICIPATION_STATUS_ENTRY set SHOW_COMMENT_TRAINING_RECORD = 'f';
alter table COURSE_PARTICIPATION_STATUS_ENTRY alter SHOW_COMMENT_TRAINING_RECORD set not null;