// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package org.phoenixctms.ctsms.domain;

import org.hibernate.criterion.Restrictions;

import org.phoenixctms.ctsms.util.L10nUtil;
import org.phoenixctms.ctsms.util.L10nUtil.Locales;
import org.phoenixctms.ctsms.vo.CriterionRestrictionVO;

/**
 * @see CriterionRestriction
 */
public class CriterionRestrictionDaoImpl
		extends CriterionRestrictionDaoBase
{

	/**
	 * @inheritDoc
	 */
	@Override
	public CriterionRestriction criterionRestrictionVOToEntity(CriterionRestrictionVO criterionRestrictionVO)
	{
		CriterionRestriction entity = this.loadCriterionRestrictionFromCriterionRestrictionVO(criterionRestrictionVO);
		this.criterionRestrictionVOToEntity(criterionRestrictionVO, entity, true);
		return entity;
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void criterionRestrictionVOToEntity(
			CriterionRestrictionVO source,
			CriterionRestriction target,
			boolean copyIfNull)
	{
		super.criterionRestrictionVOToEntity(source, target, copyIfNull);
	}

	@Override
	protected CriterionRestriction handleFindByRestriction(
			org.phoenixctms.ctsms.enumeration.CriterionRestriction restriction)
			throws Exception {
		if (restriction != null) {
			org.hibernate.Criteria restrictionCriteria = this.getSession().createCriteria(CriterionRestriction.class);
			restrictionCriteria.setCacheable(true);
			restrictionCriteria.add(Restrictions.eq("restriction", restriction));
			restrictionCriteria.setMaxResults(1);
			return (CriterionRestriction) restrictionCriteria.uniqueResult();
		} else {
			return null;
		}
	}

	/**
	 * Retrieves the entity object that is associated with the specified value object
	 * from the object store. If no such entity object exists in the object store,
	 * a new, blank entity is created
	 */
	private CriterionRestriction loadCriterionRestrictionFromCriterionRestrictionVO(CriterionRestrictionVO criterionRestrictionVO)
	{
		CriterionRestriction criterionRestriction = null;
		Long id = criterionRestrictionVO.getId();
		if (id != null) {
			criterionRestriction = this.load(id);
		}
		if (criterionRestriction == null)
		{
			criterionRestriction = CriterionRestriction.Factory.newInstance();
		}
		return criterionRestriction;
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public CriterionRestrictionVO toCriterionRestrictionVO(final CriterionRestriction entity)
	{
		return super.toCriterionRestrictionVO(entity);
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void toCriterionRestrictionVO(
			CriterionRestriction source,
			CriterionRestrictionVO target)
	{
		super.toCriterionRestrictionVO(source, target);
		target.setName(L10nUtil.getCriterionRestrictionName(Locales.USER, source.getNameL10nKey()));
	}
}