// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package org.phoenixctms.ctsms.domain;

import org.hibernate.Transaction;

/**
 * @see org.phoenixctms.ctsms.domain.Error
 */
public class ErrorDaoImpl
extends ErrorDaoBase
{

	@Override
	public void handleCreateTxn(Error error) throws Exception
	{
		// http://www.koders.com/java/fidDC3AD0DFC450E26BD45E4A8FA856716E422119F3.aspx?s=Closer
		Transaction transaction = this.getSession(true).beginTransaction();
		try {
			this.getSession().save(error);
			transaction.commit();
		} catch (Exception e) {
			transaction.rollback();
			throw e;
		}
	}
}