// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package org.phoenixctms.ctsms.domain;

import java.sql.Timestamp;
import java.util.Collection;
import java.util.HashMap;

import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.phoenixctms.ctsms.query.CriteriaUtil;
import org.phoenixctms.ctsms.query.SubCriteriaMap;
import org.phoenixctms.ctsms.security.CipherText;
import org.phoenixctms.ctsms.security.CryptoUtil;
import org.phoenixctms.ctsms.vo.PSFVO;
import org.phoenixctms.ctsms.vo.ProbandListEntryOutVO;
import org.phoenixctms.ctsms.vo.ProbandListStatusEntryInVO;
import org.phoenixctms.ctsms.vo.ProbandListStatusEntryOutVO;
import org.phoenixctms.ctsms.vo.ProbandListStatusTypeVO;
import org.phoenixctms.ctsms.vo.UserOutVO;
import org.phoenixctms.ctsms.vocycle.ProbandListStatusEntryGraph;

/**
 * @see ProbandListStatusEntry
 */
public class ProbandListStatusEntryDaoImpl
extends ProbandListStatusEntryDaoBase
{

	private org.hibernate.Criteria createStatusEntryCriteria(String alias) {
		org.hibernate.Criteria statusEntryCriteria;
		if (alias != null && alias.length() > 0) {
			statusEntryCriteria = this.getSession().createCriteria(ProbandListStatusEntry.class, alias);
		} else {
			statusEntryCriteria = this.getSession().createCriteria(ProbandListStatusEntry.class);
		}
		return statusEntryCriteria;
	}

	@Override
	protected Collection<ProbandListStatusEntry> handleFindByListEntry(
			Long probandListEntryId, PSFVO psf) throws Exception {
		org.hibernate.Criteria statusEntryCriteria = createStatusEntryCriteria(null);
		SubCriteriaMap criteriaMap = new SubCriteriaMap(ProbandListStatusEntry.class, statusEntryCriteria);
		if (probandListEntryId != null) {
			statusEntryCriteria.add(Restrictions.eq("listEntry.id", probandListEntryId.longValue()));
		}
		CriteriaUtil.applyPSFVO(criteriaMap, psf);
		return statusEntryCriteria.list();
	}

	@Override
	protected Collection<ProbandListStatusEntry> handleFindByTrialProband(
			Long trialId, Long probandId, boolean last, PSFVO psf)
					throws Exception {
		org.hibernate.Criteria statusEntryCriteria = createStatusEntryCriteria("probandListStatusEntry");
		SubCriteriaMap criteriaMap = new SubCriteriaMap(ProbandListStatusEntry.class, statusEntryCriteria);
		if (trialId != null) {
			criteriaMap.createCriteria("listEntry").add(Restrictions.eq("trial.id", trialId.longValue()));
		}
		if (probandId != null) {
			criteriaMap.createCriteria("listEntry").add(Restrictions.eq("proband.id", probandId.longValue()));
		}
		if (last) {
			criteriaMap.createCriteria("listEntry.lastStatus").add(Restrictions.eqProperty("id", "probandListStatusEntry.id")); // didn't work without explicit id compare
		}
		CriteriaUtil.applyPSFVO(criteriaMap, psf);
		return statusEntryCriteria.list();
	}

	@Override
	protected ProbandListStatusEntry handleFindLastStatus(
			Long probandListEntryId) throws Exception {
		org.hibernate.Criteria statusEntryCriteria = createStatusEntryCriteria(null);
		if (probandListEntryId != null) {
			statusEntryCriteria.add(Restrictions.eq("listEntry.id", probandListEntryId.longValue()));
		}
		statusEntryCriteria.addOrder(Order.desc("id"));
		statusEntryCriteria.setMaxResults(1);
		return (ProbandListStatusEntry) statusEntryCriteria.uniqueResult();
	}

	@Override
	protected ProbandListStatusEntry handleFindRecentStatus(
			Long trialId, Long probandId, Timestamp maxRealTimestamp)
					throws Exception {
		org.hibernate.Criteria statusEntryCriteria = createStatusEntryCriteria(null);
		if (maxRealTimestamp != null) {
			statusEntryCriteria.add(Restrictions.le("realTimestamp", maxRealTimestamp));
		}
		if (trialId != null || probandId != null) {
			Criteria listEntryCriteria = statusEntryCriteria.createCriteria("listEntry");
			if (trialId != null) {
				listEntryCriteria.add(Restrictions.eq("trial.id", trialId.longValue()));
			}
			if (probandId != null) {
				listEntryCriteria.add(Restrictions.eq("proband.id", probandId.longValue()));
			}
		}
		statusEntryCriteria.addOrder(Order.desc("realTimestamp"));
		statusEntryCriteria.addOrder(Order.desc("id"));
		statusEntryCriteria.setMaxResults(1);
		return (ProbandListStatusEntry) statusEntryCriteria.uniqueResult();
	}

	/**
	 * Retrieves the entity object that is associated with the specified value object
	 * from the object store. If no such entity object exists in the object store,
	 * a new, blank entity is created
	 */
	private ProbandListStatusEntry loadProbandListStatusEntryFromProbandListStatusEntryInVO(ProbandListStatusEntryInVO probandListStatusEntryInVO)
	{
		// TODO implement loadProbandListStatusEntryFromProbandListStatusEntryInVO
		// throw new
		// UnsupportedOperationException("org.phoenixctms.ctsms.domain.loadProbandListStatusEntryFromProbandListStatusEntryInVO(ProbandListStatusEntryInVO) not yet implemented.");
		ProbandListStatusEntry probandListStatusEntry = null;
		Long id = probandListStatusEntryInVO.getId();
		if (id != null) {
			probandListStatusEntry = this.load(id);
		}
		if (probandListStatusEntry == null)
		{
			probandListStatusEntry = ProbandListStatusEntry.Factory.newInstance();
		}
		return probandListStatusEntry;
	}

	/**
	 * Retrieves the entity object that is associated with the specified value object
	 * from the object store. If no such entity object exists in the object store,
	 * a new, blank entity is created
	 */
	private ProbandListStatusEntry loadProbandListStatusEntryFromProbandListStatusEntryOutVO(ProbandListStatusEntryOutVO probandListStatusEntryOutVO)
	{
		// TODO implement loadProbandListStatusEntryFromProbandListStatusEntryOutVO
		// throw new
		// UnsupportedOperationException("org.phoenixctms.ctsms.domain.loadProbandListStatusEntryFromProbandListStatusEntryOutVO(ProbandListStatusEntryOutVO) not yet implemented.");
		throw new UnsupportedOperationException("out value object to recursive entity not supported");
		// ProbandListStatusEntry probandListStatusEntry = this.load(probandListStatusEntryOutVO.getId());
		// if (probandListStatusEntry == null)
		// {
		// probandListStatusEntry = ProbandListStatusEntry.Factory.newInstance();
		// }
		// return probandListStatusEntry;
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public ProbandListStatusEntry probandListStatusEntryInVOToEntity(ProbandListStatusEntryInVO probandListStatusEntryInVO)
	{
		ProbandListStatusEntry entity = this.loadProbandListStatusEntryFromProbandListStatusEntryInVO(probandListStatusEntryInVO);
		this.probandListStatusEntryInVOToEntity(probandListStatusEntryInVO, entity, true);
		return entity;
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void probandListStatusEntryInVOToEntity(
			ProbandListStatusEntryInVO source,
			ProbandListStatusEntry target,
			boolean copyIfNull)
	{
		super.probandListStatusEntryInVOToEntity(source, target, copyIfNull);
		Long statusId = source.getStatusId();
		Long listEntryId = source.getListEntryId();
		if (statusId != null) {
			target.setStatus(this.getProbandListStatusTypeDao().load(statusId));
		} else if (copyIfNull) {
			target.setStatus(null);
		}
		if (listEntryId != null) {
			ProbandListEntry listEntry = this.getProbandListEntryDao().load(listEntryId);
			target.setListEntry(listEntry);
			listEntry.addStatusEntries(target);
		} else if (copyIfNull) {
			ProbandListEntry listEntry = target.getListEntry();
			target.setListEntry(null);
			if (listEntry != null) {
				listEntry.removeStatusEntries(target);
			}
		}
		try {
			if (copyIfNull || source.getReason() != null) {
				CipherText cipherText = CryptoUtil.encryptValue(source.getReason());
				target.setReasonIv(cipherText.getIv());
				target.setEncryptedReason(cipherText.getCipherText());
				target.setReasonHash(CryptoUtil.hashForSearch(source.getReason()));
			}
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public ProbandListStatusEntry probandListStatusEntryOutVOToEntity(ProbandListStatusEntryOutVO probandListStatusEntryOutVO)
	{
		ProbandListStatusEntry entity = this.loadProbandListStatusEntryFromProbandListStatusEntryOutVO(probandListStatusEntryOutVO);
		this.probandListStatusEntryOutVOToEntity(probandListStatusEntryOutVO, entity, true);
		return entity;
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void probandListStatusEntryOutVOToEntity(
			ProbandListStatusEntryOutVO source,
			ProbandListStatusEntry target,
			boolean copyIfNull)
	{
		super.probandListStatusEntryOutVOToEntity(source, target, copyIfNull);
		ProbandListStatusTypeVO statusVO = source.getStatus();
		ProbandListEntryOutVO listEntryVO = source.getListEntry();
		UserOutVO modifiedUserVO = source.getModifiedUser();
		if (statusVO != null) {
			target.setStatus(this.getProbandListStatusTypeDao().probandListStatusTypeVOToEntity(statusVO));
		} else if (copyIfNull) {
			target.setStatus(null);
		}
		if (listEntryVO != null) {
			ProbandListEntry listEntry = this.getProbandListEntryDao().probandListEntryOutVOToEntity(listEntryVO);
			target.setListEntry(listEntry);
			listEntry.addStatusEntries(target);
		} else if (copyIfNull) {
			ProbandListEntry listEntry = target.getListEntry();
			target.setListEntry(null);
			if (listEntry != null) {
				listEntry.removeStatusEntries(target);
			}
		}
		if (modifiedUserVO != null) {
			target.setModifiedUser(this.getUserDao().userOutVOToEntity(modifiedUserVO));
		} else if (copyIfNull) {
			target.setModifiedUser(null);
		}
		try {
			if (copyIfNull || source.getReason() != null) {
				CipherText cipherText = CryptoUtil.encryptValue(source.getReason());
				target.setReasonIv(cipherText.getIv());
				target.setEncryptedReason(cipherText.getCipherText());
				target.setReasonHash(CryptoUtil.hashForSearch(source.getReason()));
			}
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public ProbandListStatusEntryInVO toProbandListStatusEntryInVO(final ProbandListStatusEntry entity)
	{
		return super.toProbandListStatusEntryInVO(entity);
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void toProbandListStatusEntryInVO(
			ProbandListStatusEntry source,
			ProbandListStatusEntryInVO target)
	{
		super.toProbandListStatusEntryInVO(source, target);
		ProbandListStatusType status = source.getStatus();
		ProbandListEntry listEntry = source.getListEntry();
		if (status != null) {
			target.setStatusId(status.getId());
		}
		if (listEntry != null) {
			target.setListEntryId(listEntry.getId());
		}
		try {
			target.setReason((String) CryptoUtil.decryptValue(source.getReasonIv(), source.getEncryptedReason()));
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public ProbandListStatusEntryOutVO toProbandListStatusEntryOutVO(final ProbandListStatusEntry entity)
	{
		return super.toProbandListStatusEntryOutVO(entity);
	}

	/**
	 * @inheritDoc
	 */
	@Override
	public void toProbandListStatusEntryOutVO(
			ProbandListStatusEntry source,
			ProbandListStatusEntryOutVO target)
	{
		(new ProbandListStatusEntryGraph(this, this.getProbandListEntryDao(), this.getProbandListStatusTypeDao(), this.getUserDao())).toVOHelper(source, target,
				new HashMap<Class, HashMap<Long, Object>>());
	}

	@Override
	public void toProbandListStatusEntryOutVO(
			ProbandListStatusEntry source,
			ProbandListStatusEntryOutVO target, HashMap<Class, HashMap<Long, Object>> voMap)
	{
		(new ProbandListStatusEntryGraph(this, this.getProbandListEntryDao(), this.getProbandListStatusTypeDao(), this.getUserDao())).toVOHelper(source, target, voMap);
	}
}