package org.phoenixctms.ctsms.pdf;

public interface CVPDFSettingCodes {

	public final static String GRAPH_MAX_STAFF_INSTANCES = "graph_max_staff_instances";
	public final static String POSITION_DATE_PATTERN = "position_date_pattern";
	public final static String TEMPLATE_FILE_NAME = "template_file_name";
	public final static String FONT_A = "font_a";
	public final static String FONT_B = "font_b";
	public final static String FONT_C = "font_c";
	public final static String DATE_OF_BIRTH_DATE_PATTERN = "date_of_birth_date_pattern";
	public final static String SIGNATURE_DATE_PATTERN = "signature_date_pattern";
	public final static String LANDSCAPE = "landscape";
	public final static String PAGE_UPPER_MARGIN = "page_upper_margin";
	public final static String PAGE_LOWER_MARGIN = "page_lower_margin";
	public final static String PAGE_LEFT_MARGIN = "page_left_margin";
	public final static String PAGE_RIGHT_MARGIN = "page_right_margin";
	public final static String X_COLUMN_INDENT = "x_column_indent";
	public final static String X_COLUMN_INDENT_PHOTO = "x_column_indent_photo";
	public final static String X_FRAME_INDENT = "x_frame_indent";
	public final static String Y_FRAME_INDENT = "y_frame_indent";
	public final static String SPACER_HEIGHT = "spacer_height";
	public final static String BLOCK_FRAME_LINE_WIDTH = "block_frame_line_width";
	public final static String COLUMN_LINE_WIDTH = "column_line_width";
	public final static String PAGE_FRAME_LINE_WIDTH = "page_frame_line_width";
	public final static String BLOCKS_UPPER_MARGIN = "blocks_upper_margin";
	public final static String BLOCKS_LOWER_MARGIN = "blocks_lower_margin";
	public final static String BLOCKS_LEFT_MARGIN = "blocks_left_margin";
	public final static String BLOCKS_RIGHT_MARGIN = "blocks_right_margin";
	public final static String Y_FRAME_UPPER_INDENT_SIGNATURE = "y_frame_upper_indent_signature";
	public final static String Y_FRAME_LOWER_INDENT_SIGNATURE = "y_frame_lower_indent_signature";
	public final static String X_FRAME_INDENT_SIGNATURE = "x_frame_indent_signature";
	public final static String SIGNATURE_LINE_WIDTH = "signature_line_width";
	public final static String SIGNATURE_LINE_LENGTH = "signature_line_length";
	public final static String Y_OFFSET_SIGNATURE_ANNOTATION = "y_offset_signature_annotation";
	public static final String TEXT_COLOR = "text_color";
	public static final String FRAME_COLOR = "frame_color";
	public static final String DATE_LABEL_WIDTH = "date_label_width";
	public static final String DATE_LINE_LENGTH = "date_line_length";
	public static final String Y_IMAGE_INDENT = "y_image_indent";
	public static final String X_IMAGE_INDENT = "x_image_indent";
	public static final String SHOW_IMAGES = "show_images";
	public static final String IMAGE_WIDTH = "image_width";
	public static final String IMAGE_HEIGHT = "image_height";
	public static final String IMAGE_QUALITY = "image_quality";
	public static final String IMAGE_DPI = "image_dpi";
	public static final String SHOW_PAGE_NUMBERS = "show_page_numbers";
	public static final String IMAGE_CENTERED = "image_centered";
	public static final String PAINTER_CLASS = "painter_class";
	public static final String PAINTER_SOURCE_FILES = "painter_source_files";
	public static final String PASSED_COURSES_ONLY = "passed_courses_only";
	public static final String DATE_USER_TIME_ZONE = "date_user_time_zone";
}
